/**
 * VP(bundleName)별 레벨(beginner/intermediate/advanced) SPM 추천값 (2차, 7-9세 아동 기준).
 *
 * beginner/intermediate/advanced = API에 보낼 "요청 spm". 값은 실제 음원을 생성해
 * 청감 속도(WPM)를 실측한 뒤, 7-9세 목표(대략 B 100 / I 120 / A 137 WPM,
 * advanced 과속 방지)에 맞춰 VP별로 역산한 것. beginnerWpm/intermediateWpm/advancedWpm은
 * 그 요청값으로 실제 들리는 속도 실측치(GEMINI는 3회 중앙값).
 *
 * 핵심(scripts/spm_child_sweep.py + spm_child_confirm.py 실측):
 *  - 같은 요청 spm이라도 VP마다 실제 속도가 크게 다름(서버 baseSpm이 청감과 선형 비례가 아님).
 *    그래서 요청값을 청감 WPM 기준으로 VP별 역산.
 *  - 이 속도대(약 80~170 WPM)에서 "너무 빨라 씹힘"은 전 VP 미발생(STT 1.0).
 *  - category:
 *    "clean"   = 목표 WPM을 정확히 냄, 저rate에서도 깔끔(GCP/AWS/CHIRP/AZ-TuningAna/Ana/Xiaoyou/Sonia).
 *    "floored" = 최소속도 포화로 느린 beginner 불가(표준 Azure 다수). beginnerWpm이 실제 하한.
 *    "gemini"  = 지터 크고 저rate 침묵 위험, 3레벨 폭 좁음.
 *  - 기계음(저rate 음색)은 자동 판정 불가 -> 2차 청취로 확정.
 * TC(Typecast) 3종은 v2 미지원.
 */

export type SpmLevelCategory = "clean" | "floored" | "gemini";

export type SpmLevelRecommendation = {
  /** API 요청 spm (레벨별) */
  beginner: number;
  intermediate: number;
  advanced: number;
  /** 그 요청값으로 실제 들리는 속도(WPM) 실측 */
  beginnerWpm?: number;
  intermediateWpm?: number;
  advancedWpm?: number;
  /** 서버 Voice Profile baseSpm (rate 1.0 기준) */
  serverBaseSpm?: number;
  beginnerRate?: number;
  advancedRate?: number;
  category?: SpmLevelCategory;
  note?: string;
};

export const SPM_RECOMMENDATIONS: Record<string, SpmLevelRecommendation> = {
  "GCP-Jeremy-Default": {
    beginner: 100,
    intermediate: 120,
    advanced: 135,
    beginnerWpm: 101,
    intermediateWpm: 122,
    advancedWpm: 137,
    serverBaseSpm: 239.8,
    beginnerRate: 0.42,
    advancedRate: 0.56,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.42의 기계음 여부만 청감 확인 권장.",
  },
  "GCP-Rey-Default": {
    beginner: 90,
    intermediate: 110,
    advanced: 125,
    beginnerWpm: 100,
    intermediateWpm: 122,
    advancedWpm: 138,
    serverBaseSpm: 223.8,
    beginnerRate: 0.4,
    advancedRate: 0.56,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.4의 기계음 여부만 청감 확인 권장.",
  },
  "AWS-Justin-Default": {
    beginner: 90,
    intermediate: 110,
    advanced: 125,
    beginnerWpm: 99,
    intermediateWpm: 120,
    advancedWpm: 136,
    serverBaseSpm: 215.1,
    beginnerRate: 0.42,
    advancedRate: 0.58,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.42의 기계음 여부만 청감 확인 권장.",
  },
  "AWS-Kevin-Default": {
    beginner: 85,
    intermediate: 105,
    advanced: 125,
    beginnerWpm: 99,
    intermediateWpm: 119,
    advancedWpm: 140,
    serverBaseSpm: 227.8,
    beginnerRate: 0.37,
    advancedRate: 0.55,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.37의 기계음 여부만 청감 확인 권장.",
  },
  "CHIRP-Zephyr-Default": {
    beginner: 95,
    intermediate: 115,
    advanced: 130,
    beginnerWpm: 104,
    intermediateWpm: 123,
    advancedWpm: 146,
    serverBaseSpm: 219.2,
    beginnerRate: 0.43,
    advancedRate: 0.59,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.43의 기계음 여부만 청감 확인 권장.",
  },
  "AZ-Alfie-Default": {
    beginner: 65,
    intermediate: 80,
    advanced: 90,
    beginnerWpm: 130,
    intermediateWpm: 130,
    advancedWpm: 144,
    serverBaseSpm: 162.5,
    beginnerRate: 0.4,
    advancedRate: 0.55,
    category: "floored",
    note: "빠른 보이스: 최소 약 130WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Ana-Default": {
    beginner: 75,
    intermediate: 90,
    advanced: 105,
    beginnerWpm: 101,
    intermediateWpm: 118,
    advancedWpm: 138,
    serverBaseSpm: 149.3,
    beginnerRate: 0.5,
    advancedRate: 0.7,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.5의 기계음 여부만 청감 확인 권장.",
  },
  "AZ-Guy-Friendly": {
    beginner: 55,
    intermediate: 70,
    advanced: 80,
    beginnerWpm: 143,
    intermediateWpm: 143,
    advancedWpm: 143,
    serverBaseSpm: 163.3,
    beginnerRate: 0.34,
    advancedRate: 0.49,
    category: "floored",
    note: "빠른 보이스: 최소 약 143WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Hollie-Default": {
    beginner: 70,
    intermediate: 85,
    advanced: 95,
    beginnerWpm: 114,
    intermediateWpm: 123,
    advancedWpm: 137,
    serverBaseSpm: 157.2,
    beginnerRate: 0.45,
    advancedRate: 0.6,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.45의 기계음 여부만 청감 확인 권장.",
  },
  "AZ-Jenny-Cheerful": {
    beginner: 60,
    intermediate: 75,
    advanced: 85,
    beginnerWpm: 124,
    intermediateWpm: 124,
    advancedWpm: 136,
    serverBaseSpm: 154.9,
    beginnerRate: 0.39,
    advancedRate: 0.55,
    category: "floored",
    note: "빠른 보이스: 최소 약 124WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Maisie-Default": {
    beginner: 70,
    intermediate: 85,
    advanced: 95,
    beginnerWpm: 114,
    intermediateWpm: 121,
    advancedWpm: 135,
    serverBaseSpm: 155.8,
    beginnerRate: 0.45,
    advancedRate: 0.61,
    category: "floored",
    note: "빠른 보이스: 최소 약 114WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Nancy-Default": {
    beginner: 60,
    intermediate: 75,
    advanced: 85,
    beginnerWpm: 126,
    intermediateWpm: 127,
    advancedWpm: 140,
    serverBaseSpm: 148.0,
    beginnerRate: 0.41,
    advancedRate: 0.57,
    category: "floored",
    note: "빠른 보이스: 최소 약 126WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Oliver-Default": {
    beginner: 65,
    intermediate: 80,
    advanced: 90,
    beginnerWpm: 125,
    intermediateWpm: 125,
    advancedWpm: 139,
    serverBaseSpm: 161.4,
    beginnerRate: 0.4,
    advancedRate: 0.56,
    category: "floored",
    note: "빠른 보이스: 최소 약 125WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Sara-Friendly": {
    beginner: 60,
    intermediate: 75,
    advanced: 85,
    beginnerWpm: 125,
    intermediateWpm: 125,
    advancedWpm: 135,
    serverBaseSpm: 151.8,
    beginnerRate: 0.4,
    advancedRate: 0.56,
    category: "floored",
    note: "빠른 보이스: 최소 약 125WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Sonia-Cheerful": {
    beginner: 85,
    intermediate: 105,
    advanced: 120,
    beginnerWpm: 112,
    intermediateWpm: 124,
    advancedWpm: 137,
    serverBaseSpm: 190.3,
    beginnerRate: 0.45,
    advancedRate: 0.63,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.45의 기계음 여부만 청감 확인 권장.",
  },
  "AZ-Tony-Default": {
    beginner: 70,
    intermediate: 85,
    advanced: 95,
    beginnerWpm: 125,
    intermediateWpm: 125,
    advancedWpm: 140,
    serverBaseSpm: 168.9,
    beginnerRate: 0.41,
    advancedRate: 0.56,
    category: "floored",
    note: "빠른 보이스: 최소 약 125WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-TuningAna-Default": {
    beginner: 75,
    intermediate: 90,
    advanced: 105,
    beginnerWpm: 102,
    intermediateWpm: 119,
    advancedWpm: 138,
    serverBaseSpm: 149.3,
    beginnerRate: 0.5,
    advancedRate: 0.7,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.5의 기계음 여부만 청감 확인 권장.",
  },
  "AZ-TuningEvelyn-Default": {
    beginner: 70,
    intermediate: 85,
    advanced: 100,
    beginnerWpm: 112,
    intermediateWpm: 117,
    advancedWpm: 138,
    serverBaseSpm: 162.7,
    beginnerRate: 0.43,
    advancedRate: 0.61,
    category: "floored",
    note: "빠른 보이스: 최소 약 112WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-TuningMaisie-Default": {
    beginner: 70,
    intermediate: 85,
    advanced: 95,
    beginnerWpm: 114,
    intermediateWpm: 121,
    advancedWpm: 135,
    serverBaseSpm: 155.8,
    beginnerRate: 0.45,
    advancedRate: 0.61,
    category: "floored",
    note: "빠른 보이스: 최소 약 114WPM에서 포화(그 이하로 요청해도 더 느려지지 않음). 느린 beginner 부적합 - 빠른 캐릭터나 상위 레벨 위주 권장. 청감 확인 필요.",
  },
  "AZ-Xiaoyou-Default": {
    beginner: 90,
    intermediate: 110,
    advanced: 125,
    beginnerWpm: 107,
    intermediateWpm: 118,
    advancedWpm: 135,
    serverBaseSpm: 197.7,
    beginnerRate: 0.46,
    advancedRate: 0.63,
    category: "clean",
    note: "저rate에서도 깔끔히 느려짐(STT 1.0). beginner rate 0.46의 기계음 여부만 청감 확인 권장.",
  },
  "GEMINI-Fenrir-Cheerful": {
    beginner: 120,
    intermediate: 130,
    advanced: 150,
    beginnerWpm: 116,
    intermediateWpm: 119,
    advancedWpm: 134,
    serverBaseSpm: 159.0,
    beginnerRate: 0.75,
    advancedRate: 0.94,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Fenrir-Default": {
    beginner: 120,
    intermediate: 145,
    advanced: 160,
    beginnerWpm: 105,
    intermediateWpm: 119,
    advancedWpm: 116,
    serverBaseSpm: 160.3,
    beginnerRate: 0.75,
    advancedRate: 1.0,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Fenrir-Gentle": {
    beginner: 115,
    intermediate: 140,
    advanced: 165,
    beginnerWpm: 85,
    intermediateWpm: 148,
    advancedWpm: 122,
    serverBaseSpm: 147.3,
    beginnerRate: 0.78,
    advancedRate: 1.12,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Puck-Cheerful": {
    beginner: 120,
    intermediate: 130,
    advanced: 145,
    beginnerWpm: 128,
    intermediateWpm: 122,
    advancedWpm: 149,
    serverBaseSpm: 160.7,
    beginnerRate: 0.75,
    advancedRate: 0.9,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Puck-Default": {
    beginner: 120,
    intermediate: 135,
    advanced: 150,
    beginnerWpm: 105,
    intermediateWpm: 156,
    advancedWpm: 147,
    serverBaseSpm: 153.1,
    beginnerRate: 0.78,
    advancedRate: 0.98,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Puck-Gentle": {
    beginner: 110,
    intermediate: 130,
    advanced: 150,
    beginnerWpm: 115,
    intermediateWpm: 108,
    advancedWpm: 128,
    serverBaseSpm: 146.7,
    beginnerRate: 0.75,
    advancedRate: 1.02,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Rasalgethi-Cheerful": {
    beginner: 130,
    intermediate: 135,
    advanced: 145,
    beginnerWpm: 125,
    intermediateWpm: 87,
    advancedWpm: 132,
    serverBaseSpm: 170.3,
    beginnerRate: 0.76,
    advancedRate: 0.85,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Rasalgethi-Default": {
    beginner: 120,
    intermediate: 130,
    advanced: 150,
    beginnerWpm: 101,
    intermediateWpm: 96,
    advancedWpm: 160,
    serverBaseSpm: 160.1,
    beginnerRate: 0.75,
    advancedRate: 0.94,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Rasalgethi-Gentle": {
    beginner: 120,
    intermediate: 140,
    advanced: 165,
    beginnerWpm: 96,
    intermediateWpm: 129,
    advancedWpm: 173,
    serverBaseSpm: 160.7,
    beginnerRate: 0.75,
    advancedRate: 1.03,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Sulafat-Cheerful": {
    beginner: 120,
    intermediate: 130,
    advanced: 145,
    beginnerWpm: 95,
    intermediateWpm: 127,
    advancedWpm: 138,
    serverBaseSpm: 162.9,
    beginnerRate: 0.74,
    advancedRate: 0.89,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Sulafat-Default": {
    beginner: 120,
    intermediate: 125,
    advanced: 145,
    beginnerWpm: 96,
    intermediateWpm: 111,
    advancedWpm: 120,
    serverBaseSpm: 157.8,
    beginnerRate: 0.76,
    advancedRate: 0.92,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
  "GEMINI-Sulafat-Gentle": {
    beginner: 125,
    intermediate: 145,
    advanced: 160,
    beginnerWpm: 100,
    intermediateWpm: 97,
    advancedWpm: 144,
    serverBaseSpm: 153.9,
    beginnerRate: 0.81,
    advancedRate: 1.04,
    category: "gemini",
    note: "GEMINI 지터 큼(레벨별 실측 WPM 출렁임). beginner는 rate 0.75로 하한(그 이하는 문장 중간 침묵 삽입). 자연 tempo가 이미 브리스크해 3레벨 폭이 좁음. 청감 확인 필요.",
  },
};

export function spmRecommendationFor(
  bundleName: string,
): SpmLevelRecommendation | undefined {
  return SPM_RECOMMENDATIONS[bundleName];
}
