/**
 * VP(bundleName)별 레벨(beginner/intermediate/advanced) SPM 추천값 (3차, rate 배수 방식).
 *
 * 결정(사용자 선택): 레벨 = 각 VP baseSpm x 공통 rate 배수. 비균등, beginner 하한으로
 *   기계음 회피. rate B 0.85 / I 1.0 / A 1.18 (B-I 0.15 < I-A 0.18).
 * beginner/intermediate/advanced = API 요청 spm = round(baseSpm x rate).
 * *Wpm = 그 값으로 실제 들리는 속도 실측(고정 문장 18단어, GEMINI는 3회 중앙값).
 *
 * 핵심 실측(scripts/spm_rate_band.py):
 *  - 이 밴드에서 STT 1.0(씹힘 없음), 27/32 VP가 B<I<A로 구분됨.
 *  - category:
 *    "child"    = 레벨 구분 OK + beginner<=160WPM (7-9세 적정). GEMINI 7종뿐.
 *    "fast"     = 자연 tempo가 빨라 beginner도 167~232WPM (7-9세 과속). 비-GEMINI 20종.
 *    "collapse" = GEMINI 지터로 레벨 뭉침(구분 불확실). GEMINI 5종.
 *  - GEMINI 밴드 확대 재검증(spm_gemini_band.py): wide-low 0.78/1.02/1.30 -> beginner
 *    중간침묵 7/12, wide-safe 0.85/1.08/1.35 -> advanced 과속(일부 210~275WPM).
 *    지터로 "레벨 구분" 판정이 실행마다 바뀜. 결론: 넓혀도 안 됨, 원안 0.85/1.0/1.18 유지.
 *  - 시사점: rate 배수(자연속도 기준)에선 아동 저속이 되는 건 자연 tempo가 느린
 *    GEMINI뿐. 빠른 voice를 아동 속도로 낮추려면 더 낮은 rate가 필요(별도 결정).
 *  - 기계음(저rate 음색)은 자동 판정 불가 -> 청취 확정 필요.
 * TC(Typecast) 3종은 v2 미지원.
 */

export type SpmLevelCategory = "child" | "fast" | "collapse";

export type SpmLevelRecommendation = {
  beginner: number;
  intermediate: number;
  advanced: number;
  beginnerWpm?: number;
  intermediateWpm?: number;
  advancedWpm?: number;
  serverBaseSpm?: number;
  beginnerRate?: number;
  advancedRate?: number;
  category?: SpmLevelCategory;
  note?: string;
};

export const SPM_RECOMMENDATIONS: Record<string, SpmLevelRecommendation> = {
  "GEMINI-Fenrir-Cheerful": {
    beginner: 135,
    intermediate: 159,
    advanced: 188,
    beginnerWpm: 124,
    intermediateWpm: 167,
    advancedWpm: 209,
    serverBaseSpm: 159.0,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 124WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Fenrir-Default": {
    beginner: 136,
    intermediate: 160,
    advanced: 189,
    beginnerWpm: 139,
    intermediateWpm: 116,
    advancedWpm: 121,
    serverBaseSpm: 160.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "collapse",
    note: "GEMINI 지터로 B/I/A 레벨이 뭉침(실측 139/116/121wpm, 순서 뒤집힘). rate 밴드 좁아 구분 불확실 - 레벨 폭 확대나 레벨 수 축소 검토.",
  },
  "GEMINI-Fenrir-Gentle": {
    beginner: 125,
    intermediate: 147,
    advanced: 174,
    beginnerWpm: 98,
    intermediateWpm: 86,
    advancedWpm: 156,
    serverBaseSpm: 147.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "collapse",
    note: "GEMINI 지터로 B/I/A 레벨이 뭉침(실측 98/86/156wpm, 순서 뒤집힘). rate 밴드 좁아 구분 불확실 - 레벨 폭 확대나 레벨 수 축소 검토.",
  },
  "GEMINI-Puck-Cheerful": {
    beginner: 137,
    intermediate: 161,
    advanced: 190,
    beginnerWpm: 144,
    intermediateWpm: 190,
    advancedWpm: 190,
    serverBaseSpm: 160.7,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "collapse",
    note: "GEMINI 지터로 B/I/A 레벨이 뭉침(실측 144/190/190wpm, 순서 뒤집힘). rate 밴드 좁아 구분 불확실 - 레벨 폭 확대나 레벨 수 축소 검토.",
  },
  "GEMINI-Puck-Default": {
    beginner: 130,
    intermediate: 153,
    advanced: 181,
    beginnerWpm: 109,
    intermediateWpm: 140,
    advancedWpm: 178,
    serverBaseSpm: 153.1,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 109WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Puck-Gentle": {
    beginner: 125,
    intermediate: 147,
    advanced: 173,
    beginnerWpm: 113,
    intermediateWpm: 145,
    advancedWpm: 178,
    serverBaseSpm: 146.7,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 113WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Rasalgethi-Cheerful": {
    beginner: 145,
    intermediate: 170,
    advanced: 201,
    beginnerWpm: 132,
    intermediateWpm: 147,
    advancedWpm: 208,
    serverBaseSpm: 170.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 132WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Rasalgethi-Default": {
    beginner: 136,
    intermediate: 160,
    advanced: 189,
    beginnerWpm: 144,
    intermediateWpm: 155,
    advancedWpm: 200,
    serverBaseSpm: 160.1,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 144WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Rasalgethi-Gentle": {
    beginner: 137,
    intermediate: 161,
    advanced: 190,
    beginnerWpm: 160,
    intermediateWpm: 113,
    advancedWpm: 188,
    serverBaseSpm: 160.7,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "collapse",
    note: "GEMINI 지터로 B/I/A 레벨이 뭉침(실측 160/113/188wpm, 순서 뒤집힘). rate 밴드 좁아 구분 불확실 - 레벨 폭 확대나 레벨 수 축소 검토.",
  },
  "GEMINI-Sulafat-Cheerful": {
    beginner: 138,
    intermediate: 163,
    advanced: 192,
    beginnerWpm: 142,
    intermediateWpm: 165,
    advancedWpm: 181,
    serverBaseSpm: 162.9,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 142WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Sulafat-Default": {
    beginner: 134,
    intermediate: 158,
    advanced: 186,
    beginnerWpm: 107,
    intermediateWpm: 143,
    advancedWpm: 168,
    serverBaseSpm: 157.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "child",
    note: "레벨 구분 OK, STT 1.0. beginner 107WPM로 7-9세 적정. rate 밴드 B0.85/I1.0/A1.18.",
  },
  "GEMINI-Sulafat-Gentle": {
    beginner: 131,
    intermediate: 154,
    advanced: 182,
    beginnerWpm: 120,
    intermediateWpm: 114,
    advancedWpm: 156,
    serverBaseSpm: 153.9,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "collapse",
    note: "GEMINI 지터로 B/I/A 레벨이 뭉침(실측 120/114/156wpm, 순서 뒤집힘). rate 밴드 좁아 구분 불확실 - 레벨 폭 확대나 레벨 수 축소 검토.",
  },
  "GCP-Jeremy-Default": {
    beginner: 204,
    intermediate: 240,
    advanced: 283,
    beginnerWpm: 206,
    intermediateWpm: 243,
    advancedWpm: 284,
    serverBaseSpm: 239.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 206WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "GCP-Rey-Default": {
    beginner: 190,
    intermediate: 224,
    advanced: 264,
    beginnerWpm: 209,
    intermediateWpm: 245,
    advancedWpm: 288,
    serverBaseSpm: 223.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 209WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AWS-Justin-Default": {
    beginner: 183,
    intermediate: 215,
    advanced: 254,
    beginnerWpm: 196,
    intermediateWpm: 227,
    advancedWpm: 266,
    serverBaseSpm: 215.1,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 196WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AWS-Kevin-Default": {
    beginner: 194,
    intermediate: 228,
    advanced: 269,
    beginnerWpm: 208,
    intermediateWpm: 242,
    advancedWpm: 283,
    serverBaseSpm: 227.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 208WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "CHIRP-Zephyr-Default": {
    beginner: 186,
    intermediate: 219,
    advanced: 259,
    beginnerWpm: 195,
    intermediateWpm: 247,
    advancedWpm: 272,
    serverBaseSpm: 219.2,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 195WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Alfie-Default": {
    beginner: 138,
    intermediate: 162,
    advanced: 192,
    beginnerWpm: 212,
    intermediateWpm: 248,
    advancedWpm: 294,
    serverBaseSpm: 162.5,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 212WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Ana-Default": {
    beginner: 127,
    intermediate: 149,
    advanced: 176,
    beginnerWpm: 167,
    intermediateWpm: 195,
    advancedWpm: 231,
    serverBaseSpm: 149.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 167WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Guy-Friendly": {
    beginner: 139,
    intermediate: 163,
    advanced: 193,
    beginnerWpm: 232,
    intermediateWpm: 271,
    advancedWpm: 321,
    serverBaseSpm: 163.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 232WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Hollie-Default": {
    beginner: 134,
    intermediate: 157,
    advanced: 185,
    beginnerWpm: 193,
    intermediateWpm: 225,
    advancedWpm: 265,
    serverBaseSpm: 157.2,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 193WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Jenny-Cheerful": {
    beginner: 132,
    intermediate: 155,
    advanced: 183,
    beginnerWpm: 203,
    intermediateWpm: 238,
    advancedWpm: 280,
    serverBaseSpm: 154.9,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 203WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Maisie-Default": {
    beginner: 132,
    intermediate: 156,
    advanced: 184,
    beginnerWpm: 187,
    intermediateWpm: 221,
    advancedWpm: 260,
    serverBaseSpm: 155.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 187WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Nancy-Default": {
    beginner: 126,
    intermediate: 148,
    advanced: 175,
    beginnerWpm: 206,
    intermediateWpm: 242,
    advancedWpm: 285,
    serverBaseSpm: 148.0,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 206WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Oliver-Default": {
    beginner: 137,
    intermediate: 161,
    advanced: 190,
    beginnerWpm: 204,
    intermediateWpm: 239,
    advancedWpm: 282,
    serverBaseSpm: 161.4,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 204WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Sara-Friendly": {
    beginner: 129,
    intermediate: 152,
    advanced: 179,
    beginnerWpm: 205,
    intermediateWpm: 241,
    advancedWpm: 283,
    serverBaseSpm: 151.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 205WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Sonia-Cheerful": {
    beginner: 162,
    intermediate: 190,
    advanced: 225,
    beginnerWpm: 184,
    intermediateWpm: 216,
    advancedWpm: 256,
    serverBaseSpm: 190.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 184WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Tony-Default": {
    beginner: 144,
    intermediate: 169,
    advanced: 199,
    beginnerWpm: 205,
    intermediateWpm: 240,
    advancedWpm: 282,
    serverBaseSpm: 168.9,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 205WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-TuningAna-Default": {
    beginner: 127,
    intermediate: 149,
    advanced: 176,
    beginnerWpm: 167,
    intermediateWpm: 196,
    advancedWpm: 231,
    serverBaseSpm: 149.3,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 167WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-TuningEvelyn-Default": {
    beginner: 138,
    intermediate: 163,
    advanced: 192,
    beginnerWpm: 190,
    intermediateWpm: 215,
    advancedWpm: 252,
    serverBaseSpm: 162.7,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 190WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-TuningMaisie-Default": {
    beginner: 132,
    intermediate: 156,
    advanced: 184,
    beginnerWpm: 187,
    intermediateWpm: 220,
    advancedWpm: 260,
    serverBaseSpm: 155.8,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 187WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
  "AZ-Xiaoyou-Default": {
    beginner: 168,
    intermediate: 198,
    advanced: 233,
    beginnerWpm: 181,
    intermediateWpm: 214,
    advancedWpm: 238,
    serverBaseSpm: 197.7,
    beginnerRate: 0.85,
    advancedRate: 1.18,
    category: "fast",
    note: "자연 tempo가 빠른 voice: 이 rate 밴드에선 beginner도 181WPM. 7-9세엔 전 레벨 과속 - 아동 저속용 부적합(더 낮은 rate 필요하나 선택 밴드 밖).",
  },
};

export function spmRecommendationFor(
  bundleName: string,
): SpmLevelRecommendation | undefined {
  return SPM_RECOMMENDATIONS[bundleName];
}
